### ISSUE TITLE
Install from gem fails if there is no repository for the platform

### ISSUE THREAD

**Issue by vinzent** [puppetlabs/beaker-puppet_install_helper#27]
Running `PUPPET_INSTALL_TYPE=foss PUPPET_INSTALL_VERSION=3.8.7 BEAKER_set=fedora-24-x64 BEAKER_destroy=no bundle exec rake beaker:fedora-24-x64` fails with:

```
/home/user/.gem/ruby/gems/beaker-3.9.0/lib/beaker/host.rb:373:in `exec': Host 'fedora-24-x64' exited with 1 running: (Beaker::Host::CommandFailure)
 rpm --replacepkgs -Uvh http://yum.puppetlabs.com/puppetlabs-release-fedora-24.noarch.rpm
Last 10 lines of output were:
        curl: (22) The requested URL returned error: 404 Not Found
        Retrieving http://yum.puppetlabs.com/puppetlabs-release-fedora-24.noarch.rpm
        error: skipping http://yum.puppetlabs.com/puppetlabs-release-fedora-24.noarch.rpm - transfer failed
        from /home/user/.gem/ruby/gems/beaker-3.9.0/lib/beaker/command_factory.rb:35:in `execute'
        from /home/user/.gem/ruby/gems/beaker-3.9.0/lib/beaker/host/unix/pkg.rb:155:in `install_package_with_rpm'
        from /home/user/.gem/ruby/gems/beaker-3.9.0/lib/beaker/dsl/install_utils/foss_utils.rb:925:in `block in install_puppetlabs_release_repo_on'
        from /home/user/.gem/ruby/gems/beaker-3.9.0/lib/beaker/shared/host_manager.rb:127:in `run_block_on'
        from /home/user/.gem/ruby/gems/beaker-3.9.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
        from /home/user/.gem/ruby/gems/beaker-3.9.0/lib/beaker/dsl/install_utils/foss_utils.rb:899:in `install_puppetlabs_release_repo_on'
        from /home/user/.gem/ruby/gems/beaker-3.9.0/lib/beaker/dsl/install_utils/foss_utils.rb:439:in `block in install_puppet_from_rpm_on'
        from /home/user/.gem/ruby/gems/beaker-3.9.0/lib/beaker/shared/host_manager.rb:127:in `run_block_on'
...
```

what I tried, but did not help:

* install rubygems before puppet_install_helper (not installed by default on fedora/24-cloud-base vagrant box)
* setting `type: foss` in nodeset definition

snippet from README 

> if PUPPET_INSTALL_VERSION is less than 4 will attempt to install that version of the system package if available, or else the ruby gem of that version.

it should install the gem if there is no system package.

used gem versions:

```
#> grep beaker Gemfile.lock
    beaker (3.9.0)
      beaker-facter (~> 0.0)
      beaker-hiera (~> 0.0)
      beaker-hostgenerator
    beaker-facter (0.1.0)
    beaker-hiera (0.1.1)
    beaker-hostgenerator (0.8.2)
    beaker-puppet_install_helper (0.6.0)
      beaker (>= 2.0)
    beaker-rspec (6.0.0)
      beaker (~> 3.0)
  beaker-puppet_install_helper
  beaker-rspec

```

**Comment by DavidS** [comment]
beaker does not support installing puppet 4 as gem, and puppet 3 is EOL since the start of the year (see https://puppet.com/misc/puppet-enterprise-lifecycle). If you find a quick fix to force beaker to install the old gems, I'd be willing to merge that. Otherwise I'm more likely to just remove the claim to gem installation.

**Comment by vinzent** [comment]
just removing the docs and/or explicitly stating that puppet 3 is just not supported anymore seems fine.  even better remove the `foss` option and code related installing by gem altogheter?

I wasn't even able to install puppet 3.8.7 from gem  manually on Fedora 24 . it fails with some psych error. :) but i'm not a ruby specialist - just a puppet user and modulewriter.

**Comment by tylerjl** [comment]
+1 to explicitly documenting that 3.8 is no longer supported. The changeset from 0.6.0...0.7.0 no longer supports installing 3.8 via `PUPPET_INSTALL_TYPE=foss PUPPET_INSTALL_VERSION=3.8.7 rake ...` as far as I can determine (it looks like [this line](https://github.com/puppetlabs/beaker-puppet_install_helper/blob/c5645667ecf6184823d25adf8ec085dd3e205573/lib/beaker/puppet_install_helper.rb#L62) is installing the `pc1` repository in all cases for `foss` host types, which removes the older 3.8 repos on the host).

I'm 100% on-board with the community deprecating 3.8 since it's good and dead; I've just got some modules that are lagging behind the deprecation and thus still test against 3.8 (for now) and it'd save others some time if the documentation noted that 3.8 installations work only up to 0.6.0.
